export const LANG = {
    pl_PL: {
        blank: '---',
        selected: 'Wybrano fakturę',
        download_pdf: 'Pobierz jako PDF',
        prev_html: 'Zobacz wersję HTML',
        edit: 'Edytuj',
        send: 'Wyślij',
        options: 'Opcje',
        app: 'pl app',
        pl_PL: 'Polski',
        en_GB: 'English',
        lang_primary: 'Polski',
        lang_secondary: 'Angielski',
        invoices: 'Faktury',
        users: 'Użytkownicy',
        projects: 'Projekty',
        faq: 'FAQ',
        panel: 'Panel',
        logout: 'Wyloguj',
        data: 'Dane osobowe',
        help: 'Pomoc',
        default_correction_value: 'Na oryginalnej fakturze',
        no_content: 'Brak zawartości...',
        check_invoice: 'Sprawdź fakturę',
        name: 'Imię',
        surname: "Nazwisko",
        email: 'E-mail',
        phone: 'Numer telefonu',
        street: 'Nazwa ulicy',
        postal_code: 'Kod pocztowy',
        city: 'Miasto',
        company_data: 'Dane firmy',
        company_name: 'Nazwa firmy',
        company_type: 'Rodzaj firmy',
        bill_data: 'Dane rozliczeniowe',
        finance_data: 'Dane finansowe',
        ADD_BANK_ACC: 'Dodaj nowe konto',
        bank_name: 'Nazwa banku',
        bank_no: 'Numer rachunku bankowego',
        devices: 'Przypisany sprzęt',
        device_title: 'Nazwa urządzenia',
        select_project: 'Wybierz projekt',
        select_contractor: 'Wybierz kontraktora',
        correction_reason: 'Przyczyna korekty',
        corrections: 'Korekty',
        files: 'Pliki',
        move_files: 'Przenieś tutaj pliki',
        replace_file: 'Podmień załącznik',
        delete_file: 'Usuń załącznik',
        file_list: 'Lista plików',
        file_list_original: 'Lista plików na fakturze oryginalnej',
        confirmations: 'Potwierdzenia',
        loading: 'Ładowanie danych',
        preview: 'Podgląd',
        costs: 'Koszty dodatkowe',
        login: 'Zaloguj się',
        password: 'Hasło',
        lostpass: 'Zapomniane hasło?',
        registration: 'Rejestracja',
        save: 'Zapisz',
        invoice_title: 'Faktura',
        correction: 'korekta',
        summary: 'Podsumowanie',
        cancel: 'Anuluj',
        NIP: 'NIP',
        BANK_ACC: 'Dodatkowe numery kont bankowych',
        IBAN: 'IBAN',
        SWIFT: 'SWIFT',
        invoice_payment_currency: 'Waluta',
        to_update: 'Zmiana wartości. Oczekuję za weryfikacje.',
        invoice: {
            discount: 'Rabat',
            new: 'Nowy szkic faktury',
            details: 'Szczegóły faktury',
            send_mail: 'Wyślij fakturę na email',
            draft: 'szkic',
            in_approval: 'oczekuje na akceptację',
            rejected: 'odrzucona',
            approved: 'zaakceptowana',
            paid: 'opłacona',
            sended: 'wysłana',
            internal_number: 'Seargin - wewnętrzny numer',
            invoice_number: 'Numer faktury',
            invoice_desc: 'Opis faktury',
            description: 'Opis faktury',
            currency: 'Waluta',
            fixed_price: 'Stawka za zlecenie',
            hours_value: 'Liczba godzin',
            hours_value_netto: 'Netto',
            hours_value_gross: 'Brutto',
            issue_date: 'Data wystawienia',
            payment_date: 'Data płatności',
            sell_date: 'Data sprzedaży',
            approval: 'Zatwierdził',
            invoice_type: "Rodzaj faktury",
            invoice_basic: "Podstawowa",
            invoice_project: "Faktura na projekt",
            invoice_for_contractor: "Faktura na kontraktora",
            correction: "Korekta",
            number: "Numer faktury",
            contractor_number: "Numer faktury",
            internal_number_text: "Wewnętrzny numer faktury",
            invoice_management: "Zarządzanie fakturą",
            invoice_submit: "Prześlij fakturę do weryfikacji",
            send_: "Prześlij do akceptacji",
            nd: "Nie dotyczy",
            np: "Nie podlega",
            zw: "Zwolnienie",
            value: "Wartość",
            travels: "Podróże",
            travel_add: "Dodaj koszt związany z podróżą",
            file_confirmations: 'Potwierdzenia - pliki',
            other_costs: 'Inne koszty',
            add_other_costs: 'Dodaj inne koszty',
            remarks: 'Uwagi',
            update: 'Aktualizuj fakturę',
            create_correction: 'Faktura korygująca',
            purchaser: 'Nazwa klienta',
            vendor: 'Sprzedawca',
            submit_title: 'Potwierdź przesłanie faktury',
            submit_description: 'Faktura zostanie wysłana do weryfikacji - możliwość edycji zostanie zablokowana do momentu akceptacji przez dział Finansów Seargin'
        },
        register: {
            title: "Nowe konto",
            wrong_email: 'Zły adres email',
            verify_email: 'Weryfikuj adres email',
            next: 'Następny krok',
            verification: 'Weryfikacja',
            sms_code: 'KOD SMS',
            sms_code_type: 'Podaj kod z wiadomości SMS',
            check_sms_code: 'Weryfikuj kod',
            acc_created: 'Twoje konto zostało utworzone.',
        },
        company_type_text: {
            0: 'Działalnośc jednoosobowa',
            1: 'Spółka'
        },
        saving: 'Zapisywanie zmian...',
        overtime: 'Nadgodziny',
        oncall_10: 'On-call 10%',
        oncall_30: 'On-call 30%',
        travels: 'Podróże',
        others: 'Inne',
        send_changes: 'Prześlij dane do weryfikacji',
        make_changes: 'Zgłoś zmianę danych',
        sended: 'Dane zostały przesłane do weryfikacji',
        make_changes_helper_text: 'Twoje dane zostaną zweryfikowane, a następnie zaktualizowane',
        questionnaire: "Kwestionariusz osobowy",
        personal_data: "Dane osobowe",
        accept: "Zatwierdź wartość pola",
        address: "Adres korespondencyjny",
        resident: "Miejsce rezydencji podatkowej",
        billing: "Dane do faktury",
        vat: "Podatek VAT",
        vat_payer: "Czynny podatnik VAT",
        vat_ex: "Zwolnienie VAT",
        vat_rev: "Zagraniczny VAT (reverse charge)",
        cash: "Rozliczenie metodą kasową?",
        billing_info: "Dane rozliczeniowe",
        yes: "Tak",
        no: "Nie",
        send_main_form: "Wysyła wprowadzone dane do weryfikacji, brak możliwości zmiany wprowadzonych danych.",
        send_main_form_btn: "Prześlij kwestionariusz osobowy do weryfikacji",
        hourly_rate: "Stawka godzinowa (netto)",
        overtime_hour_rate: "Stawka za nadgodziny (netto)",
        _email: {
            title: "Tytuł wiadomości",
            default_title_text: "Faktura",
            message: "Treść wiadomości",
            default_message_text: "Oto twoja faktura"
        }
    },
    en_GB: {
        hourly_rate: "Hourly rate (netto)",
        overtime_hour_rate: "Overtime rate (netto)",
        send_main_form_btn: "Submit a personal questionnaire for verification",
        send_main_form: "Sends the entered data for verification, no possibility to change the entered data.",
        yes: "Yes",
        no: "No",
        send: "Send",
        billing_info: "Billing information",
        cash: "Cash settlement?",
        options: "Options",
        vat_payer: "Active VAT taxpayer",
        vat_ex: "VAT exemption",
        vat_rev: "Foreign VAT (reverse charge)",
        vat: "VAT Tax",
        billing: "Billing",
        resident: "Place of tax residence",
        address: "Address",
        replace_file: 'Replace file',
        delete_file: 'Delete file',
        accept: "Confirm field value",
        personal_data: "Personal data",
        blank: '---',
        edit: 'Edit',
        app: 'en app',
        pl_PL: 'Polski',
        en_GB: 'English',
        lang_primary: 'Polski',
        lang_secondary: 'English',
        invoices: 'Invoices',
        users: 'Users',
        projects: 'Projects',
        faq: 'FAQ',
        panel: 'Dashboard',
        logout: 'Logout',
        data: 'User data',
        help: 'Help',
        no_content: 'Content is missing...',
        check_invoice: 'Check invoice',
        name: 'Name',
        surname: "Surname",
        email: 'E-mail',
        phone: 'Phone number',
        street: 'Street name',
        postal_code: 'Postal code',
        city: 'City',
        BANK_ACC: 'Additional bank account numbers',
        company_data: 'Company details',
        company_name: 'Comapny name',
        company_type: 'Company type',
        bill_data: 'Billing data',
        finance_data: 'Finance data',
        bank_name: 'Bank name',
        bank_no: 'Bank account number',
        devices: 'Assigned devices',
        device_title: 'Device name',
        select_project: 'Select project',
        select_contractor: 'Select contractor',
        correction_reason: 'Reason for correction',
        corrections: 'Corrections',
        files: 'Files',
        move_files: 'Move files here',
        file_list: 'Files list',
        file_list_original: 'List of files on the original invoice',
        confirmations: 'Confirmations',
        loading: 'Loading',
        preview: 'Preview',
        costs: 'Extra costs',
        login: 'Login',
        password: 'Password',
        lostpass: 'Forgotten password?',
        registration: 'Registration',
        save: 'Save',
        invoice_title: 'Invoice',
        correction: 'Correction',
        summary: 'Summary',
        to_update: 'In veryfication...',
        cancel: 'Cancel',
        ADD_BANK_ACC: 'Add new account number',
        invoice_payment_currency: 'Currency',
        invoice: {
            discount: 'Discount',
            new: 'New invoice draft',
            details: 'Invoice details',
            send_mail: 'Send invoice via email',
            draft: 'Draft',
            in_approval: 'In approval',
            rejected: 'Rejected',
            approved: 'Approved',
            paid: 'Paid',
            sended: 'Sended',
            internal_number: 'Seargin - internal number',
            invoice_number: 'Invoice number',
            currency: 'Currency',
            fixed_price: 'The rate per order',
            invoice_desc: 'Description',
            description: 'Description',
            hours_value: 'Hours reported',
            hours_value_netto: 'Netto',
            hours_value_gross: 'Gross',
            issue_date: 'Issue date',
            payment_date: 'Expected payment date',
            sell_date: 'Sell date',
            approval: 'Approval',
            invoice_type: "Invoice type",
            invoice_basic: "Basic invoice",
            invoice_project: "Invoice for the project",
            invoice_for_contractor: "Invoice for the contractor",
            correction: "Correction",
            number: "Invoice number",
            contractor_number: "Invoice contractor number",
            internal_number_text: "Invoice internal number",
            invoice_management: "Invoice management",
            send_: "Submit for acceptance",
            nd: "Not applicable",
            np: "Is not subject to",
            zw: "Dismissal",
            value: "Value",
            travels: "Travels",
            travel_add: "Add the cost associated with the trip",
            file_confirmations: 'Confirmations - files',
            other_costs: 'Other costs',
            add_other_costs: 'Add other costs',
            remarks: 'Remarks',
            update: 'Update invoice',
            invoice_submit: "Send the invoice for verification",
            create_correction: 'Correction invoice',
            purchaser: 'Contractors',
            vendor: 'Vendor',
            submit_title: 'Confirm sending the invoice',
            submit_description: 'Your invoice will be sent to us and you will not be able to edit it.'
        },
        _email: {
            title: "Tytuł wiadomości",
            default_title_text: "Faktura",
            message: "Treść wiadomości",
            default_message_text: "Oto twoja faktura"
        },
        register: {
            title: 'Register new account',
            wrong_email: 'Sorry, this email is invalid.',
            verify_email: 'Verify email',
            next: 'Next Step',
            verification: 'Verification',
            sms_code: 'SMS CODE',
            sms_code_type: 'Type code from SMS.',
            check_sms_code: 'Verify code',
            acc_created: 'Your account has been created.',
        },
        default_correction_value: "Value on the original invoice",
        company_type_text: {
            0: 'Self-employed',
            1: 'Limited company'
        },
        overtime: 'Overtime',
        oncall_10: 'On-call 10%',
        oncall_30: 'On-call 30%',
        travels: 'Travels',
        others: 'Others',
        make_changes_helper_text: 'Your new entry will be rechecked.',
        send_changes: 'Send changes',
        make_changes: 'Update user details',
        sended: 'The data has been sent for verification',
        saving: 'Saving changes...',
        NIP: 'NIP',
        IBAN: 'IBAN',
        SWIFT: 'SWIFT',
        download_pdf: 'Save as PDF',
        selected: 'Invoice selected',
        questionnaire: 'Personal questionnaire',
        prev_html: 'Preview as HTML'
    }
};